In [32]:
import re
import pandas as pd
from datetime import datetime, date
import numpy as np

In [33]:



def is_insert(line):
    return 'INSERT INTO' in line or False

def is_create(line):
    return 'CREATE TABLE' in line or False

def is_finish(line):
    return ';' in line or False

def is_primary(line):
    return 'PRIMARY KEY' in line or False

def get_values(line):
    return line.partition(' VALUES ')[2]

def get_table_name_insert(line):
    match = re.search('INSERT INTO `([0-9_a-zA-Z]+)`', line)
    if match:
        return match.group(1)
    else:
        print(line)

def get_name_categorie_type(line):
    match = re.search('int\([0-9]+\)', line)
    if match:
        return "int"
    else:
        match = re.search('char', line)
        if match:
            return match.group(0)
        else:
            match = re.search('date', line)
            if match:
                return match.group(0)
            else:
                match = re.search('time', line)
                if match:
                    return match.group(0)
                else:
                    match = re.search('text', line)
                    if match:
                        return match.group(0)
                    else:
                        print(line)
              
def get_table_name_create(line):
    match = re.search('CREATE TABLE IF NOT EXISTS `([0-9_a-zA-Z]+)`', line)
    if match:
        return match.group(1)
    else:
        print(line)
        
def get_name_categorie(line):
    match = re.search('`([0-9_a-zA-Z]+)`', line)
    if match:
        return match.group(1)
    else:
        print(line)
      
def get_columns(line):
    match = re.search('INSERT INTO `.*` \(([^\)]+)\)', line)
    if match:
        return list(map(lambda x: x.replace('`', '').strip(), match.group(1).split(',')))

def parse_line(line):
    if line[0] == "(": 
        line = line[1:-2]
        line = line.split(", ")
    return line
    
def sqltopanda(filename):
    d = {}
    type_categorie = {}
    values = []
    table_name = []
    columns = []
    insert = False
    create = False
    reader = open(filename, 'r', encoding='utf-8')
    contenu = reader.read()
    lines = contenu.split("\n")
    j =0
    
    for line in lines:
        if is_insert(line):
            insert = True
        elif is_create(line):
            table = get_table_name_create(line)
            d[get_table_name_create(line)] = pd.DataFrame()
            type_categorie[get_table_name_create(line)] = []
            create = True
        elif is_finish(line) and create:
            create = False
        if create and not is_create(line) and not is_primary(line):
            d[table][get_name_categorie(line)] = ""
            type_categorie[table].append(get_name_categorie_type(line))
        if (insert and not is_insert(line)) or (is_finish(line) and insert):
            dictio = {}
            values = parse_line(line)         
            for i in range(len(values)):
                if values[i] == "NULL":
                    d[table][list(d[table].columns)[i]] = values[i]
                elif type_categorie[table][i] == "int":
                    values[i] = int(values[i])
                elif type_categorie[table][i] == "char":
                    values[i] = str(values[i])
                elif type_categorie[table][i] == "date":
                    values[i] = datetime.strptime(values[i], "'%Y-%m-%d'").date()
                elif type_categorie[table][i] == "time":
                    values[i] = datetime.strptime(values[i], "'%H:%M:%S'").time()
                else:
                    print(type_categorie[table][i], values[i], type(values[i]))
                dictio[d[table].columns[i]] = values[i]
            d[table] = d[table].append(dictio, ignore_index=True)
            if is_finish(line) and insert:
                insert = False
    return d, type_categorie

# current date and time
deb = datetime.now()
sql, type_categorie = sqltopanda("traceforum.sql")
fin = datetime.now()
print("déubt =", sql)
print("fin =", type_categorie)

déubt = {'activite':    IDAct                                              Titre TypeAct IDCat
0      1                       'Visiter un lien hypertexte'       0     1
1      2             'Afficher une structure (cours,forum)'       0     1
2      3      'Afficher les titres des message d''un forum'       1     1
3      4                'Afficher le contenu d''un message'       1     2
4      5                                        'Connexion'       0     3
5      6  'Plier et deplier l''aborescence d''une struct...       2     1
6      7                              'Bouger la ScrollBar'       2     1
7      8  'Bouger la Scrollbar en bas (afficher la fin d...       2     1
8      9                            'Repondre a un message'       1     2
9     10                        'Poster un nouveau message'       1     2
10    11                       'Modifier le thème de forum'       0     4, 'categorie':   IDCat                                          Titre
0     1                            'Parcours du forum'
1     2  'Operation sur les messages de communication'
2     3                         'Communication privee'
3     4                         'Personnalisation IHM', 'transition':       IDTran Utilisateur                                   Titre  \
0          1  'tdelille'                             'Connexion'
1          2  'tdelille'  'Afficher une structure (cours/forum)'
2        166      'mmay'                 'Répondre à un message'
3        165      'mmay'         'Afficher le fil de discussion'
4        163      'mmay'         'Afficher le fil de discussion'
...      ...         ...                                     ...
26241  26507      'mmay'                             'Connexion'
26242  26508     'admin'                             'Connexion'
26243  26509     'admin'  'Afficher une structure (cours/forum)'
26244  26510     'admin'     'Afficher le contenu d''un message'
26245  26511     'admin'     'Afficher le contenu d''un message'

                                   Attribut        Date     Heure Delai  \
0                          'login=tdelille'  2009-02-12  11:33:55  NULL
1                               'IDForum=7'  2009-02-12  11:33:58  NULL
2      'IDForum=7,IDMsg=1184,IDParent=1183'  2009-02-13  03:40:13  NULL
3                    'IDForum=7,IDMsg=1163'  2009-02-13  03:30:13  NULL
4                    'IDForum=7,IDMsg=1163'  2009-02-13  03:27:50  NULL
...                                     ...         ...       ...   ...
26241                          'login=mmay'  2009-05-11  16:21:53  NULL
26242                         'login=admin'  2010-05-10  14:25:54  NULL
26243                         'IDForum=326'  2010-05-10  14:26:00  NULL
26244               'IDForum=326,IDMsg=877'  2010-05-10  14:26:42  NULL
26245               'IDForum=326,IDMsg=879'  2010-05-10  14:26:52  NULL

      RefTran Commentaire
0           0        NULL
1           0        NULL
2           0        NULL
3           0        NULL
4           0        NULL
...       ...         ...
26241       0        NULL
26242       0        NULL
26243       0        NULL
26244       0        NULL
26245       0        NULL

[26246 rows x 9 columns], 'typeu':   IDTypeU                       Titre
0       1            'Membre inscrit'
1       2  'Invite avec mot de passe'
2       3  'invite sans mot de passe'
3       4                   'Anonyme', 'userfiles':     ID             User IDForum IDMsg                              Filenameo  \
0    1  'mwollenburger'       7  1218                     'Visite musee.doc'
1    2       'tdelille'     353  1530                    'Festivals Tat.doc'
2    3  'ddaniaupotter'     353  1543             'tableau festival t+d.pdf'
3    4  'mwollenburger'     353  1544      'Reperage sites festivals MW.doc'
4    5        'gachort'     353  1551        'FESTIVALS panorama rapide.doc'
..  ..              ...     ...   ...                                    ...
90  91         'mdanet'     339  2983                'Guide Pedagogique.pdf'
91  92       'jvasseur'      17  2986  'Scene4 - prise finale_questions.doc'
92  93         'mdanet'     339  3024                'Guide Pedagogique.doc'
93  94       'jvasseur'     339  3032                'Guide_Pedagogique.doc'
94  95        'mgodwod'     339  3034                        'Objectifs.doc'

               Filenamer Filetype     Filesize  Dateupload Timeupload  \
0   '20090215142525.doc'   '.doc'   '14.50 KB'  2009-02-15   14:25:44
1   '20090228013652.doc'   '.doc'   '46.00 KB'  2009-02-28   01:38:58
2   '20090301102246.pdf'   '.pdf'  '120.48 KB'  2009-03-01   10:23:06
3   '20090301103801.doc'   '.doc'   '24.50 KB'  2009-03-01   10:38:09
4   '20090301133455.doc'   '.doc'   '30.50 KB'  2009-03-01   13:35:05
..                   ...      ...          ...         ...        ...
90  '20090427223157.pdf'   '.pdf'  '200.43 KB'  2009-04-27   22:32:12
91  '20090428041658.doc'   '.doc'   '29.00 KB'  2009-04-28   04:17:11
92  '20090429134731.doc'   '.doc'  '186.50 KB'  2009-04-29   13:47:47
93  '20090429190015.doc'   '.doc'  '186.00 KB'  2009-04-29   19:00:25
94  '20090430093324.doc'   '.doc'   '45.50 KB'  2009-04-30   09:34:53

       Date_la   Time_la Nbdownload Filestatus
0   2009-02-16  02:33:48          0          0
1   2009-03-18  04:25:02          3          0
2   2009-03-22  12:45:22          4          0
3   2009-03-18  04:27:06          3          0
4   2009-03-02  14:40:37          2          0
..         ...       ...        ...        ...
90  2009-04-28  06:26:51          1          0
91  2009-04-28  06:33:01          2          0
92  2009-04-29  14:34:24          2          0
93  2009-04-30  08:47:26          0          0
94  2009-04-30  10:10:39          2          0

[95 rows x 14 columns], 'usertool': Empty DataFrame
Columns: [IDUser, Name, Surname, Email, Login, Password, Type, Comment]
Index: [], 'usertool_notes': Empty DataFrame
Columns: [IDNote, Username, Share, Nbmax, Note, Date, Lastaccess]
Index: [], 'usertool_param':   IDParam Paramname1 Paramvalue1 Description1 Paramname2 Paramvalue2  \
0       1  'sortout'      'DESC'         NULL   'colour'         '1'

  Description2      Paramname3 Paramvalue3 Description3     Paramname4  \
0         NULL  'timeinterval'         '2'         NULL  'scrollspeed'

  Paramvalue4 Description4  Username
0         '2'         NULL  'madeth'  , 'usertool_sharenote': Empty DataFrame
Columns: [IDShare, Username, IDNote, Dateshare, Lastaccess]
Index: [], 'utilisateur': Empty DataFrame
Columns: [IDU, Usager, Trace, IDTypeU]
Index: []}
fin = {'activite': ['int', 'char', 'int', 'int'], 'categorie': ['int', 'char'], 'transition': ['int', 'char', 'char', 'char', 'date', 'time', 'time', 'int', 'char'], 'typeu': ['int', 'char'], 'userfiles': ['int', 'char', 'int', 'int', 'char', 'char', 'char', 'char', 'date', 'time', 'date', 'time', 'int', 'int'], 'usertool': ['int', 'char', 'char', 'char', 'char', 'char', 'char', 'char'], 'usertool_notes': ['int', 'char', 'int', 'int', 'text', 'date', 'date'], 'usertool_param': ['int', 'char', 'char', 'char', 'char', 'char', 'char', 'char', 'char', 'char', 'char', 'char', 'char', 'char'], 'usertool_sharenote': ['int', 'char', 'int', 'date', 'date'], 'utilisateur': ['int', 'char', 'int', 'int']}

In [50]:
def nbActions(Action, Utilisateur):
    return sql['transition'][(sql['transition']['Titre'] == Action) & (sql['transition']['Utilisateur'] == Utilisateur)].count()['IDTran']

In [52]:
Action = ["'Répondre à un message'", "'Poster un nouveau message'"]


for utilisateur in sql['transition']["Utilisateur"].unique().tolist():
    for act in Action:
        nbActions(act, utilisateur)

In [36]:
def postsUtilisateur(utilisateur):
    tab = []
    attribut = sql['transition']['Attribut'][(sql['transition']['Titre'] == "'Poster un nouveau message'") & (sql['transition']['Utilisateur'] == utilisateur)]
    for attr in attribut:
        tab.append(str(attr).split(",")[1].split("\n")[0].split("=")[1][:-1])
    return(tab)
    
    
def getReponsesPost(idParent):
    utilisateur = sql['transition']['Utilisateur'][(sql['transition']['Attribut'].str.contains('IDParent='+idParent)) & (sql['transition']['Titre'] == "'Répondre à un message'")]
    attribut = sql['transition']['Attribut'][(sql['transition']['Attribut'].str.contains('IDParent='+idParent))]
    if(attribut.empty):
        return ("", "")
    idMessage = str(attribut).split(",")[1].split("\n")[0].split("=")[1]
    return (utilisateur, idMessage)

In [53]:
#pour chaque utilisateur

utilisateurs = sql['transition']["Utilisateur"].unique().tolist()
for utilisateur in utilisateurs:
    if(nbActions("'Poster un nouveau message'", utilisateur) == 0):
        print(utilisateur, "test")

68
7
68
39
0
3
0
3
41
27
1
2
6
10
32
2
0
13
8
2
15
1
0

In [14]:

for l in range(len(utilisateurs)):
    print("\n Pour l'utilisateur :" + utilisateurs[l] +"\n" )
    #on initialise la matrice de résultat
    a = np.zeros(shape=(1,len(utilisateurs)))
    tableauResultat = pd.DataFrame(a, index = ['l1'], columns = utilisateurs)
    #on recupere les posts qu'il a créé
    posts = postsUtilisateur(utilisateurs[l])
    
    #pour chaque post qu'il a créé
    for i in range(len(posts)):
        tableauUsers = []
        user, idMessage = getReponsesPost(posts[i])
        #tant qu'il y a des messages on déroule le fil de la discussion
        while idMessage != "" :  
            #on récupere l'identifiant du message et l'utilisateur qui a posté le message
            tableauUsers.append(user.values[0])
            user, idMessage = getReponsesPost(idMessage)
        tableauUsers = list(set(tableauUsers))
       
        # on ajoute 1 dans la matrice si l'utilisateur a répondu au post
        for j in range(len(utilisateurs)):
            for k in range(len(tableauUsers)):
                if tableauUsers[k] == utilisateurs[j]:
                    tableauResultat.at['l1', utilisateurs[j]] = (1 + tableauResultat.at['l1', utilisateurs[j]])
   
    # on calcule la matrice en pourcentage
    if (len(posts) != 0) :
        tableauResultat = (tableauResultat * 100) / len(posts)
    print(tableauResultat)
fin = datetime.now()
print(deb)
print(fin)

 Pour l'utilisateur :'tdelille'

    'tdelille'    'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1   52.941176  5.882353        48.529412  29.411765          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0        23.529412  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'mmay'

    'tdelille'     'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1   28.571429  42.857143        14.285714  28.571429          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0        14.285714  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'ddaniaupotter'

    'tdelille'    'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1   69.117647  2.941176        42.647059  32.352941          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0        32.352941  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'gachort'

    'tdelille'    'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1   43.589744  5.128205        33.333333  43.589744          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0        23.076923  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'sebastien'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0              0.0  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'admin'

    'tdelille'     'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1   33.333333  66.666667              0.0  33.333333          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0              0.0  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'madeth'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0              0.0  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'cdejean'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0  33.333333   66.666667              0.0  ...   33.333333

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'fdarriet'

    'tdelille'    'mmay'  'ddaniaupotter'  'gachort'  'sebastien'   'admin'  \
l1         0.0  2.439024              0.0        0.0          0.0  2.439024

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0  14.634146   46.341463              0.0  ...   29.268293

     'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1  51.219512       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'mwollenburger'

    'tdelille'     'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1   37.037037  11.111111        55.555556  33.333333          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0        44.444444  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'tsoubrie'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1       100.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0              0.0  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'insauser1'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0              0.0  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'mgodwod'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0   33.333333              0.0  ...   33.333333

     'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1  33.333333       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'jvasseur'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0    20.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0        30.0              0.0  ...        50.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1      30.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'mdanet'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1       3.125    6.25              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0      9.375      34.375              0.0  ...      21.875

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1    28.125       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'psalam'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0              0.0  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0      50.0      0.0      100.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'guest'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0              0.0  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'cevanen'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0              0.0  ...         0.0

    'mdanet'   'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0  23.076923      0.0  23.076923  15.384615               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0     7.692308         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'cfroger'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0              0.0  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0       25.0       12.5               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'adebeuckelaere'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0              0.0  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'shernu'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0              0.0  ...         0.0

    'mdanet'   'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0  13.333333      0.0   6.666667        0.0          6.666667

    'shernu'  'xjmechain'  'ntricoit'
l1  6.666667          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'xjmechain'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0              0.0  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]

 Pour l'utilisateur :'ntricoit'

    'tdelille'  'mmay'  'ddaniaupotter'  'gachort'  'sebastien'  'admin'  \
l1         0.0     0.0              0.0        0.0          0.0      0.0

    'madeth'  'cdejean'  'fdarriet'  'mwollenburger'  ...  'jvasseur'  \
l1       0.0        0.0         0.0              0.0  ...         0.0

    'mdanet'  'psalam'  'guest'  'cevanen'  'cfroger'  'adebeuckelaere'  \
l1       0.0       0.0      0.0        0.0        0.0               0.0

    'shernu'  'xjmechain'  'ntricoit'
l1       0.0          0.0         0.0

[1 rows x 23 columns]
2019-11-08 14:21:18.791870
2019-11-08 14:21:48.231374

In [15]:
def getReponses(action, utilisateur):
     return(sql['transition'][(sql['transition']['Titre'] == action) & (sql['transition']['Utilisateur'] == utilisateur)])

def getMessage(idMsg):
     return(sql['transition'][((sql['transition']['Titre'].str.contains('Répondre à un message'))
                              |sql['transition']['Titre'].str.contains('Poster un nouveau message'))
                             & sql['transition']['Attribut'].str.contains('IDMsg='+idMsg)])


def getDifferenceMessages(dateMessage, timeMessage, dateParent, timeParent):
    return(datetime.combine(dateMessage, timeMessage) - datetime.combine(dateParent, timeParent)).total_seconds()




def temps_moyen(seconds):
    intervals = (
    ('semaines', 604800),  # 60 * 60 * 24 * 7
    ('jours', 86400),    # 60 * 60 * 24
    ('heures', 3600),    # 60 * 60
    ('minutes', 60),
    ('secondes', 1),
    )
    result = []
    for name, count in intervals:
        value = seconds // count
        if value:
            seconds -= value * count
            if value == 1:
                name = name.rstrip('s')
            result.append("{} {}".format(value, name))
    return ', '.join(result[:5])

In [16]:
#Pour chaque utilisateur
for utilisateur in sql['transition']["Utilisateur"].unique().tolist():
    #on récupere toutes les réponses de l'utilisateur
    reponses = getReponses("'Répondre à un message'", utilisateur)
    tabDuree = 0
    i = 0
    #pour chaque reponse on récupère la date du message
    for reponse in reponses.values:
        i = i+1
        dateMessage = reponse[4]
        timeMessage = reponse[5]
        timeParent = reponse[2][5]
        #on recupere l'id du message auquel il a répondu
        idParent = reponse[3].split(",")[2].split("=")[1][:-1]
        #on recupere le message auquel il a répondu
        msgParent = getMessage(idParent)
        #si on trouve le message auquel il a répondu on récupre la date du message
        if(len(msgParent.values) != 0):
            dateParent = msgParent.values[0][4]
            timeParent = msgParent.values[0][5]
            #on calcul le temps de réponse
            tabDuree = tabDuree + getDifferenceMessages(dateMessage, timeMessage, dateParent, timeParent)
    #on fait la moyenne du temps de réponse 
    if(i != 0):
        print(temps_moyen(tabDuree/i))

4.0 heures, 29.0 minutes, 57.0 secondes
10.0 heures, 24.0 minutes, 11.0 secondes
5.0 heures, 43.0 minutes, 25.0 secondes
3.0 heures, 51.0 minutes, 7.0 secondes
12.0 heures, 13.0 minutes, 29.0 secondes
2.0 jours, 1.0 heure, 4.0 minutes, 30.0 secondes
14.0 heures, 49.0 minutes, 39.0 secondes
7.0 heures, 27.0 minutes, 23.0 secondes
1.0 jour, 12.0 heures, 15.0 minutes, 10.0 secondes

8.0 heures, 1.0 minute, 7.0 secondes
11.0 heures, 14.0 minutes, 23.0 secondes
9.0 heures, 58.0 minutes, 57.0 secondes
2.0 jours, 4.0 heures, 58.0 minutes, 58.0 secondes
1.0 jour, 7.0 heures, 25.0 minutes, 49.0 secondes
1.0 jour, 9.0 heures, 23.0 minutes, 22.0 secondes
3.0 jours, 19.0 heures, 30.0 minutes, 48.0 secondes
47.0 secondes
5.0 heures, 51.0 minutes, 22.0 secondes